MIR_ROS_HOST = 'localhost'
MIR_ROS_PORT = 9090
MIR_AUTHORIZATION_CODE = 'xxx'

MIR_MISSION_GROUP_ID = 'c444fe63-d3a1-11e8-8c41-b8aeed74d1d4'
MIR_MISSION_NAME = 'Go to position'
MIR_MOVE_TO_POS_ACTION_TYPE = 'move_to_position'
MIR_RELATIVE_MOVE_ACTION_TYPE = 'relative_move'