['/map_metadata', 
'/move_base_node/local_costmap/obstacles', 
'/move_base_node/MIRPlannerROS/cost_cloud', 
'/move_base/feedback', 
'/move_base_node/global_costmap/unknown_space', 
'/proximity_sensors/filtered_cloud', 
'/ultrasonic_sensors/range_filter/head_right', 
'/move_base_node/parameter_descriptions', '/LightCtrl/us_list', 
'/robot_mode', 
'/ultrasonic_sensors/time_filter/side_left', 
'/mirwebapp/laser_map_metadata', 
'/move_base_node/MIRPlannerROS/global_plan', 
'/ultrasonic_sensors/raw_data/side_left', 
'/move_base/status', 
'/robot_status', 
'/changes/positions', 
'/b_raw_scan', 
'/particlevizmarker', 
'/MissionController/CheckArea/visualization_marker', 
'/one_way_map', 
'/mirEventTrigger/events', 
'/wifi_diagnostics/roam_events', 
'/skid_detection_likelihood', 
'/marker_tracking_node/laser_line_extract/parameter_descriptions', 
'/move_base_node/traffic_costmap/obstacles', 
'/session_importer_node/info', 
'/MC/currents', 
'/active_mapping_guid', 
'/mirwebapp/web_path', 
'/SickPLC/parameter_descriptions', 
'/hook/status', 
'/move_base_node/global_costmap/robot_footprint', 
'/move_base_node/traffic_costmap/inflated_obstacles', 
'/scan', '/mir_amcl/parameter_updates', 
'/move_base_node/current_goal', 
'/ultrasonic_sensors/time_filter/side_right', 
'/move_base_node/global_costmap/obstacles', 
'/ultrasonic_sensors/range_filter/head_left', 
'/f_scan', '/move_base_node/visualization_marker', 
'/MissionController/goal_position_guid', 
'/laser_back/driver/parameter_descriptions', 
'/ultrasonic_sensors/time_filter/head_right', 
'/PB/gpio/input', 
'/move_base_node/global_costmap/inflated_obstacles', 
'/move_base_node/MIRPlannerROS/parameter_descriptions', 
'/wifi_diagnostics/wifi_ap_time_stats', 
'/scan_filter/visualization_marker', 
'/move_base_node/parameter_updates', 
'/marker_tracking_node/goal', 
'/marker_tracking_node/result', 
'/odom_enc', 
'/localization_score', 
'/laser_front/driver/parameter_updates', 
'/mir_status_msg', 
'/camera_floor_right/background', 
'/move_base/goal', 
'/MissionController/prompt_user', 
'/scan_filter/parameter_descriptions', 
'/SickPLC/parameter_updates', 
'/diagnostics_toplevel_state', 
'/joystick_vel', 
'/ultrasonic_sensors/time_filter/head_left', 
'/camera_floor/background', 
'/ultrasonic_sensors/raw_data/head_right',
 '/camera_top/obstacles', '/marker_tracking_node/cancel', 
 '/laser_front/driver/parameter_descriptions', 
 '/camera_top/background', '/traffic_map', 
 '/resource_tracker/needed_resources', 
 '/wifi_diagnostics', '/stall_detection', 
 '/mir_cmd', '/tf', '/camera_floor/obstacles',
  '/marker_tracking_node/status', 
  '/ultrasonic_sensors/pointcloud_combined', 
  '/move_base_node/MIRPlannerROS/len_to_goal', 
  '/move_base_node/MIRPlannerROS/parameter_updates', 
  '/move_base_node/traffic_costmap/parameter_descriptions', 
  '/ultrasonic_sensors/raw_data/head_left', '/move_base_node/global_plan', '/set_mc_PID', '/ultrasonic_sensors/range_filter/side_right', '/param_update', '/wifi_diagnostics/wifi_ap_interface_stats', '/tf_static', '/robot_state', '/diagnostics', '/cmd_vel', '/marker_tracking_node/laser_line_extract/parameter_updates', '/rosout', '/move_base_node/traffic_costmap/parameter_updates', '/ultrasonic_sensors/prediction_filter/side_left', '/marker_tracking_node/laser_line_extract/visualization_marker', '/rosout_agg', '/safety_status', '/move_base_node/traffic_costmap/unknown_space', '/move_base_node/local_costmap/safety_zone', '/ultrasonic_sensors/range_filter/side_left', '/check_pose_area/polygon', '/MC/encoders', '/robot_tracker/tracked_robots', '/MC/battery_voltage', '/skid_detection_cusum', '/ultrasonic_sensors/raw_data/side_right', '/move_base/cancel', '/areas', '/ultrasonic_sensors/prediction_filter/head_left', '/move_base_node/local_costmap/robot_footprint', '/amcl_pose', '/move_base_node/MIRPlannerROS/visualization_marker', '/LightCtrl/charging_state', '/ultrasonic_sensors/prediction_filter/side_right', '/marker_tracking_node/feedback', '/LightCtrl/bms_data', '/move_base_node/local_costmap/parameter_descriptions', '/odom', '/move_base_node/local_costmap/inflated_obstacles', '/final_optimization_progress', '/move_base_node/SBPLLatticePlanner/plan', '/light_cmd', '/imu_data', '/skid_detection_measurments', '/f_raw_scan', '/mir_amcl/selected_points', '/move_base_node/traffic_costmap/robot_footprint', '/move_base_simple/goal', '/robot_tracker/robots_pointcloud', '/camera_floor_left/obstacles', '/move_base_node/global_costmap/parameter_updates', '/mir_amcl/parameter_descriptions', '/scan_filter/parameter_updates', '/camera_floor_right/obstacles', '/move_base_node/time_to_coll', '/move_base_node/SBPLLatticePlanner/sbpl_lattice_planner_stats', '/map', '/laser_back/driver/parameter_updates', '/mirwebapp/grid_map_metadata', '/move_base_node/global_costmap/parameter_descriptions', '/b_scan', '/wifi_diagnostics/cur_ap', '/move_base_node/MIRPlannerROS/updated_global_plan', '/move_base_node/MIRPlannerROS/local_plan', '/move_base_node/SBPLLatticePlanner/visualization_marker', '/initialpose', '/move_base_simple/visualization_marker', '/mirspawn/node_events', '/MC/battery_currents', '/camera_floor_left/background', '/move_base_node/local_costmap/unknown_space', '/mir_log', '/move_base_node/local_costmap/parameter_updates', '/move_base/result', '/move_base_node/mir_escape_recovery/visualization_marker', '/ultrasonic_sensors/prediction_filter/head_right', '/diagnostics_agg', '/robot_pose', '/check_area/polygon'
]